variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  key: "$CI_BUILD_REF_NAME"   # Keep cache across branch
  paths:
    - $CI_PROJECT_DIR/.m2/repository

stages:                   # List of stages for jobs, and their order of execution
  - build
  - test

build:
  stage: build
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - echo "Building the code..."
    - mvn $MAVEN_CLI_OPTS $MAVEN_OPTS clean install -Dmaven.test.skip=true
    - echo "Build complete."
  artifacts:
    paths:
      - target/
  only:
    - master
  tags:
    - docker-executor

test:
  stage: test
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - echo "Testing the code..."
    - mvn $MAVEN_CLI_OPTS $MAVEN_OPTS test
    - mvn $MAVEN_CLI_OPTS $MAVEN_OPTS jacoco:report
    - echo "Test complete."
  artifacts:
    reports:
      junit: target/surefire-reports/*.xml
    paths:
      - target/site/jacoco/
  only:
    - master
  tags:
    - docker-executor