# Identyfikator projektu w SonarQube
sonar.projectKey=object-oriented-programming-2_templates_java-maven-template_AZK0a-SOcFOkTi-Mf4ut

# Nazwa wy?wietlana w SonarQube
sonar.projectName=Example Project

# Wersja projektu
sonar.projectVersion=1.0

# ?cie?ka do katalogu ?róde?
sonar.sources=src/main/java

# ?cie?ka do katalogu z testami
sonar.tests=src/test/java

# ?cie?ka do katalogu wyklucze? (je?li chcesz wykluczy? pliki z analizy)
# sonar.exclusions=**/*.generated.*

# U?ycie Javy jako j?zyka projektu
sonar.language=java

# Kompilator u?ywa Javy 17
sonar.java.source=17

# U?yj raportu Jacoco do analizy pokrycia testami
sonar.java.coveragePlugin=jacoco
sonar.jacoco.reportPaths=target/site/jacoco/jacoco.xml

# ?cie?ka do pliku z wynikami testów jednostkowych
sonar.junit.reportPaths=target/surefire-reports

sonar.qualitygate.wait=true
sonar.sourceEncoding=UTF-8